data:
  drug_name: "abexinostat"
  drug_setting: "scRNAseq" 
  where: "latent_space"

model:
  epsilon: 1e-1

  vector_field:
    num_layers: 3
    latent_embed_dim: 256
    condition_embed_dim: 256
    t_embed_dim: 256
    joint_hidden_dim: 256
    n_frequencies: 128
    act_fn: "silu"

  bridge:
    bridge_type: "constant"
    num_layers: 3
    hidden_dim: 256
    act_fn: "silu"
    beta: 0.

  ot_solver:
    threshold: 1e-3
    momentum:
      value: 1.
      start: 25
      
optim:
  learning_rate: 1e-3
  weight_decay: 1e-5
  batch_size_source: 1_024
  batch_size_target: 1_024
  num_iterations: 20_000

callback:
  use_callback: True
  callback_freq: 1_000
  evaluation_in_data_space: True
  kwargs:
    epsilon: 1e-1
    num_sample_conditional: 10
    seed: 0
  log_wandb: True

  


  
  