wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693997525.874486
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 45
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 45
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.10.10
      5: 0.14.2
      8:
      - 1
      - 5
